### ISSUE TITLE
Consider changing `novoda-blogs` to just blogs

### ISSUE THREAD

**Issue by tasomaniac** [novoda/dashboard-plugins#3]
Consider changing the code for `novoda-blogs` to just blogs or rss and make it configurable and support any rss page.

**Comment by ouchadam** [comment]
The reason for making it `novoda` specific was due to the way we parse the rss feed.

We're using 

```javascript
    return {
        title: item.title,
        showDescription: item.title.length < 20,
        description: item.description,
        author: item['dc:creator'],
        image: item['media:content'] ? item['media:content']['$'].url : null,
        date: formatDateString(item.pubDate)
    }
```
Which may not work with other feeds./

We could be super explicit declaring the fields we require in the feed and then allow the url to be passed in?

**Comment by tasomaniac** [comment]
Are these not standard? Documenting the expectations is a good idea. We should do that. It will at least work fine with Ghost backed blogs. If not, it will also be easier for others to contribute.

**Comment by ouchadam** [comment]
I'm not entirely sure, would need to check! 

I know that podcast rss feeds can vary depending on if they're from an apple feed provider.

**Comment by juankysoriano** [comment]
Closing as this repository is no longer under maintenance and it's about to be archived
